templateRepository:
  gitProvider: myGitIntegration
  path: "ifsemail9/jfrog-pipelines"
  branch: main
  templateFolder: templates/artifactory/cleanup/artifact-cleanup

publishTemplate:
  namespace: ifs
  name: artifactCleanup
  version: 1.0.0
  pipelineName: publish_artifact_cleanup_template
  artifactoryIntegration: myArtIntegration
  jfrogAccessTokenIntegration: myAccessTokenIntegration
